config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names:
  {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  }
  
  resources :porfolios, except: [:show] do 
    put :sort , on: :collection
  end     
  get 'angular-items', to: 'porfolios#angular'
  
  get 'porfolio/:id', to: 'porfolios#show', as: :'porfolio_show'
    
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  
  resources :blogs do 
    member do 
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'
  
  root 'pages#home', as: :home
end

app/views/shared/_application_footer.html.erb
<div class="row copy-section">
  <div class="container">
    <footer>
        <p class="app-footer"><%= copyright_generator %></p>
    </footer>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="row">
  <div class="container app-header">
    <h3 class="masthead-brand">Jient DoNgoc</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>
 

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">Jient on Rails</h1>
    <p class="lead blog-description">
      <span class="blog-element"></span>
    </p>
    <span>
      <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
    </span>
    <span>
      <%= link_to "Topics", topics_path %>
    </span>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-dark bg-dark blog-nav">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="container">
    <%= link_to "JientDoNgoc", home_path, class: 'navbar-brand' %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%= nav_helper 'nav-link', 'li' %>  
        <%= login_helper 'nav-link' %>  
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>I'm a Programmer <em> >> Photographer</em> >> Dreamer >></p>
  </div>
  
  <%= source_helper("alert alert-info blog-sidebar-source") %>
  
  <div class="sidebar-module">
    <h4>Topics</h4>
    <% @side_bar_topics.each do |topic| %>
      <p><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>

  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/JientDoNgoc"><%= fa_icon "github" %></a></li>
      <li><a href="https://www.facebook.com/JientDoNgoc"><%= fa_icon "facebook" %></a></li>
      <li><a href="https://jientdongoc.tumblr.com/"><%= fa_icon "tumblr" %></a></li>
    </ol>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", home_path %></div>
  <div><%= link_to "About", about_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Portfolio", porfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "View All Portfolio Items", porfolios_path %> / 
      <a href="#">Back to top</a>
    </p>
    <p>
    <%= copyright_generator %>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">
      In this portfolio I've listed some of my pet projects
      that I've built through the years.</p>
    <p>
      <%= link_to 'Find Out More About Me', about_path, class: 'btn btn-primary' %>
      <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-md-7 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">I'm Thuy Oanh or you can call me Jient </br>
          My hobbies are reading books, traveling, coding.</br></br>
          >>NANer || NAKer || NHCer || HCMUPer >></br>
          ______________________________________________________ </br>
 
          >> Programmer >> Photographer >> Dreamer >> </br>
          ______________________________________________________ </br>
      
          >> Change what you can and accept what you cannot!!! >></p>
      </div>
      <div class="col-sm-4 offset-md-1 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li' %>
          <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="navbar navbar-dark bg-dark box-shadow">
  <div class="container d-flex justify-content-between">
    <%= link_to "Jient DoNgoc", home_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>