config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names:
  {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  }
  
  resources :porfolios, except: [:show] do 
    put :sort , on: :collection
  end     
  get 'angular-items', to: 'porfolios#angular'
  
  get 'porfolio/:id', to: 'porfolios#show', as: :'porfolio_show'
    
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  
  resources :blogs do 
    member do 
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'
  
  root 'pages#home', as: :home
end

app/models/porfolio.rb
class Porfolio < ApplicationRecord
    has_many :technologies
    accepts_nested_attributes_for :technologies, 
                                    allow_destroy: true,
                                    reject_if: lambda {|attrs| attrs['name'].blank?}

    validates_presence_of :title, :body
    
    mount_uploader :thumb_image, PorfolioUploader
    mount_uploader :main_image, PorfolioUploader
    
    def self.angular
        where(subtitle: 'Angular')
    end
    
    def self.by_position
        order("position ASC")
    end
    
    scope :ruby_on_rails_portfolio_items, -> {where(subtitle: 'Ruby on Rails')} 
end

app/controllers/porfolios_controller.rb
class PorfoliosController < ApplicationController
  before_action :set_porfolio_item, only: [:edit, :show, :update, :destroy]
  layout "porfolio"
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all
  
    def index
    @porfolio_items = Porfolio.by_position
    end
    
    def sort
      params[:order].each do |key, value|
        Porfolio.find(value[:id]).update(position: value[:position])
      end
      render nothing: true
    end
    
    def angular
    @angular_portfolio_items = Porfolio.angular
    end
    
    def new
    @porfolio_item = Porfolio.new
    end
    
    def create
    @porfolio_item = Porfolio.new(porfolio_params)
    
    respond_to do |format|
      if @porfolio_item.save
        format.html { redirect_to porfolios_path, notice: 'Porfolio item is now live.' }
      else
        format.html { render :new }
      end
    end
    end
    
    def edit
    @porfolio_item = Porfolio.find(params[:id])
    end
    
    def update
    @porfolio_item = Porfolio.find(params[:id])    

    respond_to do |format|
      if @porfolio_item.update(porfolio_params)
        format.html { redirect_to porfolios_path, notice: 'Your portfolio item was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
    end
    
    def show
    @porfolio_item = Porfolio.find(params[:id])    
    end

    def destroy
    @porfolio_item = Porfolio.find(params[:id])
    
    @porfolio_item.destroy
        respond_to do |format|
          format.html { redirect_to porfolios_path, notice: 'Your portfolio item successfully destroyed.' }
          format.json { head :no_content }
        end
    end
    
    private 
    def porfolio_params
      params.require(:porfolio).permit(:title, 
                                       :subtitle,
                                       :body,
                                       :main_image,
                                       :thumb_image,
                                       technologies_attributes: [:id, :name, :_destroy])
    end
    
    def set_porfolio_item
      @porfolio_item = Porfolio.find(params[:id])
    end
  
end

app/helpers/porfolios_helper.rb
module PorfoliosHelper
  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end

  def porfolio_img img, type
    if img.model.main_image? || img.model.thumb_image?
      img
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    elsif type == 'main'
      image_generator(height: '600', width: '400')
    end
  end
end

app/views/porfolios/_form.html.erb
<%= form_for(@porfolio_item) do |f| %>
  <% if @porfolio_item.errors.any? %>
    <% @porfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <label class="btn btn-primary">
          Upload a main image file <%= f.file_field :main_image, style: 'display:none;' %>
        </label>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a thumb image file <%= f.file_field :thumb_image, style: 'display:none;' %>
        </label>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', rows: 13 %>
      </div>
    </div>
  </div>

  <hr>

  <div class="col-md-12">
    <h2>Technolgies Used:</h2>
    <div>
      <%= f.fields_for :technologies do |technology_form| %>
        <%= render 'technology_fields', f: technology_form %>
      <% end %>
    </div>
    
    <div>
      <%= link_to_add_association 'Add Technology', f, :technologies %>
    </div>

    <div class="form-group">
      <%= f.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/porfolios/_porfolio_item.html.erb
<div class="col-md-4">
  <div class="card" data-id="<%= porfolio_item.id %>">
    <%= image_tag porfolio_img(porfolio_item.thumb_image, 'thumb'), width: '100%' %>
    <p class="card-text">
      <span><%= link_to porfolio_item.title, porfolio_show_path(porfolio_item) %></span> <%= porfolio_item.subtitle %>
    </p>
  </div>
</div>

app/views/porfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/porfolios/angular.html.erb
<h3>Angular Portfolio Items</h3>

<%= link_to "Create New Item", new_porfolio_url if logged_in?(:site_admin) %>

<%= @angular_portfolio_items.each do |porfolio_items| %>
    <p><%= link_to porfolio_items.title, porfolio_show_path(porfolio_items.id) %></p>
    <p><%= porfolio_items.subtitle %></p>
    <p><%= porfolio_items.body %></p>
    <%= image_tag porfolio_items.thumb_image unless porfolio_items.thumb_image.nil? %>
    <%= link_to "edit", edit_porfolio_path(porfolio_items.id) if logged_in?(:site_admin) %>
    <%= link_to "delete portfolio item", porfolio_path(porfolio_items.id), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
<% end %>

app/views/porfolios/edit.html.erb
<div class="container portfolio-container">
  <h1>Edit this Portfolio Item</h1>

  <%= render 'form', porfolio_item: @porfolio_item %>
</div>

app/views/porfolios/index.html.erb
<div class="album text-muted">
  <div class="container">
    <%= source_helper("alert alert-warning") %>
    
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
      <%= render partial: 'porfolio_item', collection: @porfolio_items %>
    </div>
  </div>
</div>

app/views/porfolios/new.html.erb
<div class="container portfolio-container">
  <h1>Create a new Portfolio Item</h1>

  <%= render 'form', porfolio_item: @porfolio_item %>
</div>

app/views/porfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag porfolio_img(@porfolio_item.main_image, 'main'), width: '100%' %>
    </div>

    <div class="col-md-5">
      <h1><%= @porfolio_item.title %></h1>

      <hr>

      <em><%= @porfolio_item.subtitle %></em>

      <p><%= @porfolio_item.body %></p>

      <hr>

      <h3>Technologies Used:</h3>

      <% @porfolio_item.technologies.each do |t| %>
      <p><%= t.name %></p>
      <% end %>
      
      <% if logged_in?(:site_admin) %>
        <div class="">
          <%= link_to "Edit Item", edit_porfolio_path(@porfolio_item), class: 'btn btn-warning' %>
          <%= link_to "Delete Item", @porfolio_item, method: :delete, data: { confirm: 'Are you sure you want to delete this item' }, class: 'btn btn-danger' %>
        </div>
      <% end %>
    </div>
  </div>
</div>